# Generated by Django 4.1.5 on 2023-02-09 17:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_posts_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='joined_forums',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_profile_picture',
            field=models.ImageField(default='profile_pictures/user-profile-icon.png', upload_to='profile_pictures/'),
        ),
    ]
