# Generated by Django 4.1.5 on 2023-02-06 15:37

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userprofile_joined_forums_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('posts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.posts')),
                ('title', models.CharField(max_length=200)),
                ('contentvalue', models.TextField()),
                ('link', models.CharField(blank=True, max_length=200)),
            ],
            bases=('account.posts',),
        ),
        migrations.AlterField(
            model_name='forums',
            name='members',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='posts',
            name='comments',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=2), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='posts',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
