# Generated by Django 4.1.5 on 2023-02-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_content_alter_forums_members_alter_posts_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forums',
            name='privacy',
            field=models.CharField(default='public', max_length=200),
        ),
    ]
