# Generated by Django 4.1.5 on 2023-02-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_forums_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='post_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
