# Generated by Django 4.1.5 on 2023-02-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_content_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='link',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
