# Generated by Django 4.1.6 on 2023-02-20 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_userprofile_joined_forums_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notify_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notifications',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
